# Generated by Django 5.2.10 on 2026-01-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '赛事类型',
                'verbose_name_plural': '赛事类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('level', models.CharField(choices=[('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0+')], default='3.5', max_length=10, verbose_name='技术水平')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '参赛选手',
                'verbose_name_plural': '参赛选手',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='赛事名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='举办地点')),
                ('description', models.TextField(blank=True, verbose_name='赛事简介')),
                ('status', models.CharField(choices=[('upcoming', '即将举行'), ('ongoing', '进行中'), ('finished', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype', verbose_name='赛事类型')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='队伍名称')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event', verbose_name='赛事')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player1', to='events.player', verbose_name='选手1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_player2', to='events.player', verbose_name='选手2')),
            ],
            options={
                'verbose_name': '双打队伍',
                'verbose_name_plural': '双打队伍',
                'unique_together': {('event', 'team_name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('quarter', '1/4决赛'), ('semi', '半决赛'), ('final', '决赛')], max_length=20, verbose_name='轮次')),
                ('match_number', models.PositiveIntegerField(verbose_name='场次编号')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='比分')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='events.event', verbose_name='赛事')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_team1', to='events.team', verbose_name='队伍1')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_team2', to='events.team', verbose_name='队伍2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='events.team', verbose_name='胜方')),
            ],
            options={
                'verbose_name': '对阵比赛',
                'verbose_name_plural': '对阵比赛',
                'unique_together': {('event', 'round', 'match_number')},
            },
        ),
    ]
